name: NPM Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish-npm:

    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Lint code
        run: npm run lint
      - run: |
          TAG=$(echo $GITHUB_REF_NAME | grep -oP '^v\d+\.\d+\.\d+-?\K(\w+)?')
          npm publish --tag ${TAG:-latest} --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
